[package]
name = "bibcon"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lazy_static = "1"
regex = "1"
biblatex = "0.6"
clap = "2"

[profile.release]
strip = true
opt-level = 1
